### ISSUE TITLE
[Error] Can not resolve configuration property '...

### ISSUE THREAD

**Issue by jyajoo** [ITE-2023/BookReport#22]
yml에서 property를 설정해준 것을 인식하지 못하는 문제 발생

```yaml
book:
  id: ~~
  secret: ~~
  searchUrl: ~~
```

```java
@Value("${book.searchUrl")
private String BOOK_SEARCH_URL;

@Value("${book.id}")
private String ID;

@Value("${book.secret")
private String SECRET;
```
yml에서 인식하지 못하기 때문에 위의 필드에 값이 제대로 주어지지 않는 문제
